apiVersion: v1
kind: Service
metadata:
  namespace: gic6
  name: pgpool-stats
  labels:
    app: pgpool-stats
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9719"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: pgpool
  ports:
  - name: pgpool-stats-port
    protocol: TCP
    port: 9719
    targetPort: 9719