apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: gic6
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - name: prometheus-port
    protocol: TCP
    port: 9090
    targetPort: 9090