apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: gic6
data:
  nginx.conf: |
    user  nginx;

    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;

    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      
      default_type  application/octet-stream;

      sendfile        on;

      access_log      on;

      log_format syslog_format '$remote_addr - - [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\"';

      server {
        listen 80 default_server;
        server_name app.gic6.k3s;

        access_log syslog:server=127.0.0.1:5531,facility=local7,tag=nginx syslog_format;

        location /api/ {
          # proxy_pass http://app:8080/;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   Host      $http_host;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_pass http://misago-service:8000/api/;
        }

        location /nginx_status {
          stub_status on;
          access_log  on;
          allow all;
        }

        location / {
          # proxy_pass http://app:8080/;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   Host      $http_host;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_pass http://misago-frontend-service:8001/;
        }

        location /promopage {
          root /static/;
          index index.html;
        }
        
        location /static {
          root /;
        }
      }
    }