apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: gic6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx        # default nginx image
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - name: static-files
              mountPath: /data
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: nginx-static-pvc
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf