apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: gic6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4040"
    spec:
      containers:
        - image: nginx        # default nginx image
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - name: static-files
              mountPath: /static
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
        # - name: exporter
        #   ports:
        #     - name: exporter
        #       containerPort: 9113
        #   image: nginx/nginx-prometheus-exporter:0.8.0
        #   args:
        #     - -nginx.scrape-uri=http://localhost/nginx_status
        - name: exporter
          ports:
            - name: exporter
              containerPort: 4040
          image: quay.io/martinhelmich/prometheus-nginxlog-exporter:stable
          args: ["-config-file", "/etc/prometheus-nginxlog-exporter/config.hcl"]
          volumeMounts:
            - name: exporter-config
              mountPath: /etc/prometheus-nginxlog-exporter/config.hcl
              subPath: config.hcl
      restartPolicy: Always
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: nginx-static-pvc
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: exporter-config
          configMap:
            name: exporter-config
            items:
              - key: config.hcl
                path: config.hcl
 