apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-static-pvc
  namespace: gic6 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
