apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: gic6
spec:
  selector:
    app: postgresql-db
  clusterIP: None
  ports:
    - name: psql
      port: 5432
      targetPort: 5432
    - name: pg-exporter
      port: 9187
      targetPort: 9187
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres-exporter
#  namespace: gic6
#spec:
#  selector:
#    app: postgresql-db
#  clusterIP: None
#  ports:
#    - port: 9187
#      targetPort: 9187