apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: gic6
spec:
  minReadySeconds: 10
  serviceName: postgres-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:10
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /var/lib/postgresql/data
              subPath: data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
      volumes:
        - name: postgresql-db-disk
          persistentVolumeClaim:
            claimName: postgresql-db-pvc