apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-db-pvc
  namespace: gic6
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi