global:
  scrape_interval: 20s      # time between each scrape (data pull from exporters), can be overrided in specific jobs
  evaluation_interval: 20s  # time between each evaluation of Prometheus' alerting rules
  # external_labels:
  #   monitor: 'gic6-monitor'
rule_files:
  - /etc/prometheus/prometheus.rules
# alerting:
#   ...

scrape_configs:
- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'postgres-exporter'
  static_configs:
    - targets:
      - pg-exporter.gic6.k3s
      # - localhost:9187

- job_name: 'nginx-exporter'
  static_configs:
    - targets:
      - localhost:9010
