#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: prometheus
#  namespace: gic6
#
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: prometheus
#  namespace: gic6

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: gic6